#import "./fragments/weblink.graphql"
#import "./fragments/vote.graphql"
#import "./fragments/commentChild.graphql"

mutation AddComment($body: String, $channel: ID, $files: [ID!], $parent: ID) {
  addComment(body: $body, channel: $channel, files: $files, parent: $parent) {
    id
    body
    dateCreated
    files {
      id
      filename
      type
    }
  }
}

mutation UpdateComment($id: ID!, $body: String, $files: [ID!]) {
  updateComment(id: $id, body: $body, files: $files) {
    id
    body
    files {
      id
      filename
      name
      type
      size
    }
  }
}

mutation DeleteComment($id: ID!) {
  deleteComment(id: $id)
}

mutation ToggleVote($post: ID!) {
  toggleVote(post: $post)
}

query Comment($id: ID!) {
  comment(id: $id) {
    id
    body
    dateCreated
    dateEdited
    parent
    channel
    voteNum
    votes {
      ...VoteFields
    }
    user {
      id
      name
      avatar
    }
    files {
      id
      filename
      name
      type
      size
    }
    weblinks {
      ...WeblinkFields
    }
    children {
      ...CommentChildFields
    }
  }
}
