query Notes {
  notes {
    id
    title
    body
    dateCreated
    dateEdited
  }
}

query Note($id: ID!) {
  note(id: $id) {
    id
    title
    body
    dateCreated
    dateEdited
  }
}

mutation AddNote($body: String, $title: String) {
  addNote(body: $body, title: $title) {
    id
    title
    body
    dateCreated
    dateEdited
  }
}

mutation UpdateNote($id: ID!, $body: String, $title: String) {
  updateNote(id: $id, body: $body, title: $title) {
    id
    title
    body
    dateCreated
    dateEdited
  }
}

mutation DeleteNote($id: ID!) {
  deleteNote(id: $id)
}
